/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.upflix.applovin;

import com.applovin.sdk.AppLovinPrivacySettings;
import com.applovin.sdk.AppLovinSdk;
import com.applovin.sdk.AppLovinSdkConfiguration;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="AppLovin", id="com.upflix.applovin")
public class AppLovinModule extends KrollModule
{
	// Standard Debugging variables
	public static String MODULE_NAME = "AppLovin";
	private static final String LCAT = "AppLovinModule";
	private static final boolean DBG = TiConfig.LOGD;

	public static String AD_UNIT_ID;
	public static String AD_COLOUR = "#000000";

	@Kroll.constant public static final String AD_LOADED = "ad_loaded";
	@Kroll.constant public static final String AD_DISPLAYED = "ad_displayed";
	@Kroll.constant public static final String AD_HIDDEN = "ad_hidden";
	@Kroll.constant public static final String AD_LOAD_FAILED = "ad_load_failed";
	@Kroll.constant public static final String AD_DISPLAY_FAILED = "ad_display_failed";
	@Kroll.constant public static final String AD_CLICKED = "ad_clicked";
	@Kroll.constant public static final String AD_EXPANDED = "ad_expanded";
	@Kroll.constant public static final String AD_COLLAPSED = "ad_collapsed";
	@Kroll.constant public static final String AD_NOT_READY = "ad_not_ready";

	@Kroll.constant public static final String REWARDED_VIDEO_STARTED = "rewarded_video_started";
	@Kroll.constant public static final String REWARDED_VIDEO_COMPLETED = "rewarded_video_completed";
	@Kroll.constant public static final String USER_REWARDED = "user_rewarded";


	public AppLovinModule()
	{
		super();
	}

	public static AppLovinModule getModuleInstance() {
		TiApplication appContext = TiApplication.getInstance();
		AppLovinModule module = (AppLovinModule) appContext.getModuleByName(MODULE_NAME);
		return module;
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created

		// Make sure to set the mediation provider value to "max" to ensure proper functionality
		AppLovinSdk.getInstance( TiApplication.getInstance() ).setMediationProvider( "max" );
		AppLovinSdk.initializeSdk( TiApplication.getInstance(), new AppLovinSdk.SdkInitializationListener() {
			@Override
			public void onSdkInitialized(final AppLovinSdkConfiguration configuration) {
				Log.d(LCAT, "-- All Adapters are ready to request ads --");
			}
		} );
	}

	@Kroll.method
	public static void setHasUserConsent(boolean hasUserConsent){
		// Consent Flags in GDPR and Other Regions
		AppLovinPrivacySettings.setHasUserConsent( hasUserConsent, TiApplication.getInstance() );
	}

	@Kroll.method
	public static void setIsAgeRestrictedUser(boolean isAgeRestrictedUser){
		// Prohibition on Personal Information from Children
		AppLovinPrivacySettings.setHasUserConsent( isAgeRestrictedUser, TiApplication.getInstance() );
	}

	@Kroll.method
	public static void setDoNotSell(boolean doNotSell){
		// California Consumer Privacy Act (“CCPA”)
		AppLovinPrivacySettings.setHasUserConsent( doNotSell, TiApplication.getInstance() );
	}
}

