/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.upflix.applovin;

import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;

// This proxy can be created by calling TiAndroidAppLovin.createView({message: "hello world"})
@Kroll.proxy(creatableInModule = AppLovinModule.class)
public class MrecProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String LCAT = "MrecProxy";
	private static final boolean DBG = TiConfig.LOGD;

	private MrecView Mrec;

	// Constructor
	public MrecProxy()
	{
		super();
		Log.d(LCAT, "createMrec()");
	}

	@Override
	public TiUIView createView(Activity activity) {
		Mrec = new MrecView(this);
		return Mrec;
	}
}
